apiVersion: v1
kind: ReplicationController
metadata:
  name: myingnx-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    version: 2.6.1
  template:
    metadata:
      labels:
        app: myjavaapp
        version: 2.6.1
    spec:
      containers:
        - name: myjavaappcontainer
          image: raiyan19/myjavaapp23sep22
          ports:
            - containerPort: 80
