apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: myjavaapp
    version: 2.6.1
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector: 
    app: myjavaapp
    version: 2.6.1
